### ISSUE TITLE
Relax constraints on requirements

### ISSUE THREAD

**Issue by mahrz24** [chhantyal/parquet-cli#2]
Is it possible to relax the requirements (lower and upper bound) or are the exact pinned versions needed?

**Comment by chhantyal** [comment]
Hmm, good question :D There are two hard requirements: I think `pandas` can work, but `pyarrow` needs to be `0.9.0.post1` as I am using some feature only available in that version.

May I ask what is motivation? Guess it is updating your existing installation?

**Comment by bjfelton** [comment]
The pyarrow 0.9.0.post1 version is only available on Mac (see https://github.com/apache/arrow/issues/1950).  The rest of us are unable to use this.

**Comment by chhantyal** [comment]
Thanks @bjfelton for that information.
I am not sure how to fix this now. If I pin version to 0.9.0, it will break for OSX.

**Comment by chhantyal** [comment]
Hi @bjfelton , I fixed above issue here https://github.com/chhantyal/parquet-cli/commit/45e1f69d16dfdbc0dc3cc3bd753e7c0957fb306b

And uploaded new version to PyPi.

`pip install parquet-cli==1.2`

Let me know if it works. Thanks
